# Generated by Django 4.0.3 on 2023-01-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user_cart',
            field=models.JSONField(default=None),
        ),
    ]
