# Generated by Django 4.0.3 on 2023-01-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usercart_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user_cart',
            field=models.JSONField(blank=True),
        ),
    ]
