# Generated by Django 4.0.3 on 2023-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usercart_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
