# Generated by Django 4.0.3 on 2023-01-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usercart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
